services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      networks:
        static_network:
          ipv4_address: ${DB_HOST}
      ports:
        - '5432:5432'

  api_app:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/app
    networks:
      static_network:
        ipv4_address: ${API_HOST}
    ports:
      - '8001:80'
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  static_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1