name: Deploy to aws

on:
  workflow_run:
    workflows: ["Format Code"]
    types:
      - completed

env:
    AWS_REGION: eu-north-1
    ECR_REPO: practice-image-repository

jobs:

#    test:
#        name: App test
#        runs-on: ubuntu-latest
#        needs: lint

    deploy:
        name: Creata & deploy image
        runs-on: ubuntu-latest
        needs: lint

        steps:
              - name: Checkout repository
                uses: actions/checkout@v4

              - name: Set up aws cli
                uses: aws-actions/configure-aws-credentials@v2
                with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

              - name: Login to ECR
                id: ecr-login
                uses: aws-actions/amazon-ecr-login@v1

              - name: Build Docker image
                run: docker build -t my-app .

              - name: Tag & push image
                run: |
                    docker tag my-app:latest ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO }}:latest
                    docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO }}:latest


              - name: Update ECS cluster
                run: |
                  aws ecs update-service \
                    --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
                    --service ${{ secrets.ECS_SERVICE_NAME }} \
                    --force-new-deployment \
                    --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100" \
                    --health-check-grace-period-seconds 60
